version: '3'

services:
  web:
    build: .
    ports:
      - '80:8000'
    volumes:
      - .:/app/src
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
